# config/packages/validator.yaml
framework:
  validation:
    email_validation_mode: html5
    auto_mapping:
      App\Entity\: true

    mapping:
      paths:
        - '%kernel.project_dir%/config/validator/validation.yaml'
