<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZAcJxTG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZAcJxTG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZAcJxTG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZAcJxTG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZAcJxTG\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZAcJxTG',
    'container.build_id' => '39c377f1',
    'container.build_time' => 1729112078,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZAcJxTG');
